# Generated by Django 5.2.14 on 2026-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_episode_item_not_null"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0055_user_jellyfin_mark_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home_layout",
            field=models.CharField(
                choices=[("list", "List"), ("grid", "Grid")],
                default="list",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("home_layout__in", ["list", "grid"])),
                name="home_layout_valid",
            ),
        ),
    ]
